REFERENCE=$1
REFERENCE_NAME=${REFERENCE##*/}
REFERENCE_NAME=${REFERENCE_NAME%*.*}

FILE_NAME=$2

HASH_NAME=$REFERENCE_NAME".hash"
HASH_LOCATION=$PWD"/"$HASH_NAME

WORKING_DIR=$FILE_NAME"_reads"
cd $WORKING_DIR

SMALT_BIN="/software/hpag/bin/smalt-0.7.4"
SSAHA_SHRED_BIN="/nfs/users/nfs_z/zn1/bin/ssaha_shred"

SHRED_SIZE=200
$SSAHA_SHRED_BIN -rlength $SHRED_SIZE $REFERENCE $REFERENCE_NAME"-shred-"$SHRED_SIZE"bp.fasta"
$SMALT_BIN map -m 20 -f ssaha -n 4 -O -d 0 $HASH_LOCATION $REFERENCE_NAME"-shred-"$SHRED_SIZE"bp.fasta" > "shred_map"
cd ..

